# Generated by Django 5.2.1 on 2025-05-15 04:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_after_days', models.PositiveIntegerField(default=30, help_text='Number of days after which images are automatically archived.')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload the image file.', upload_to='images/')),
                ('location', models.CharField(help_text='Location where the image was taken.', max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the image was uploaded.')),
                ('archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(help_text='Uploader.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='The rating value (1-5).')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Date and time when the rating was given.')),
                ('image', models.ForeignKey(help_text='The image being rated.', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='image_upload.image')),
                ('user', models.ForeignKey(help_text='The user who gave the rating.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('image', 'user')},
            },
        ),
    ]
