# Generated by Django 5.2.1 on 2025-05-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0002_alter_image_timestamp_alter_image_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_after_days', models.PositiveIntegerField(default=30)),
            ],
        ),
    ]
