# Generated by Django 5.2.1 on 2025-05-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0003_alter_image_options_image_approved_image_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
        migrations.RemoveField(
            model_name='image',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(default='2025-05-14 12:35:34.628418+00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='2024-01-01 10:00:00', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 10:00:00'),
            preserve_default=False,
        ),
    ]
