# Generated by Django 5.2.1 on 2025-05-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0005_alter_image_options_image_location_image_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
