# Generated by Django 5.2.1 on 2025-05-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='uploaded_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.AddField(
            model_name='image',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
