# Generated by Django 5.2.1 on 2025-05-14 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_rename_title_image_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='image',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(default='Description not provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
