# Generated by Django 5.2.1 on 2025-05-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_rename_user_image_title_remove_image_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
