# Generated by Django 5.2.1 on 2025-05-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
